"""Template placeholder to localization-key mapping."""

from __future__ import annotations

UI_TOKENS = {
    "__NAV_OVERVIEW__": "nav.overview",
    "__NAV_DRILL__": "nav.drill",
    "__NAV_EXPLORE__": "nav.explore",
    "__NAV_TOUR__": "nav.tour",
    "__MAP_STRUCTURAL__": "map.structural",
    "__MAP_DOMAIN__": "map.domain",
    "__MAP_KNOWLEDGE__": "map.knowledge",
    "__ACTION_FIT__": "action.fit",
    "__ACTION_PATH__": "action.path",
    "__ACTION_FILTER__": "action.filter",
    "__ACTION_EXPORT__": "action.export",
    "__ACTION_FLOW__": "action.flow",
    "__ACTION_THEME__": "action.theme",
    "__ACTION_REFRESH__": "action.refresh",
    "__ACTION_HELP__": "action.help",
    "__ACTION_DIFF__": "action.diff",
    "__ACTION_FUNCTIONS__": "action.functions",
    "__ACTION_FACETS__": "action.facets",
    "__DETAIL_FILES__": "detail.files",
    "__DETAIL_CLASSES__": "detail.classes",
    "__SEARCH_FUZZY__": "search.fuzzy",
    "__SEARCH_SEMANTIC__": "search.semantic",
    "__SEARCH_NODES__": "label.search_nodes",
    "__LABEL_TOOLS__": "label.tools",
    "__LABEL_ANALYSIS__": "label.analysis",
    "__LABEL_DETAIL__": "label.detail",
    "__LABEL_SEARCH__": "label.search",
    "__LABEL_ACTIONS__": "label.actions",
    "__MODAL_PATH_TITLE__": "modal.path_title",
    "__MODAL_FIND_PATH__": "modal.find_path",
    "__MODAL_CLEAR__": "modal.clear",
    "__PANEL_SOURCE__": "panel.source",
    "__TERMINAL_TITLE__": "terminal.title",
    "__TERMINAL_SUBTITLE__": "terminal.subtitle",
    "__HELP_TITLE__": "help.title",
    "__HELP_SUBTITLE__": "help.subtitle",
    "__HELP_GENERAL__": "help.general",
    "__HELP_NAVIGATION__": "help.navigation",
    "__HELP_VIEW_MODES__": "help.view_modes",
    "__HELP_GUIDED_TOUR__": "help.guided_tour",
    "__HELP_FOCUS_SEARCH__": "help.focus_search",
    "__HELP_FILTER_PANEL__": "help.filter_panel",
    "__HELP_EXPORT_MENU__": "help.export_menu",
    "__HELP_THEME_MENU__": "help.theme_menu",
    "__HELP_TERMINAL__": "help.terminal",
    "__HELP_TOGGLE_HELP__": "help.toggle_help",
    "__HELP_CLOSE_PANEL__": "help.close_panel",
    "__HELP_FIT_GRAPH__": "help.fit_graph",
    "__HELP_RESET_FIT__": "help.reset_fit",
    "__HELP_ZOOM__": "help.zoom",
    "__HELP_PAN__": "help.pan",
    "__HELP_PATH_FINDER__": "help.path_finder",
    "__HELP_FOCUS_NODE__": "help.focus_node",
    "__HELP_DOMAIN_TOGGLE__": "help.domain_toggle",
    "__HELP_KNOWLEDGE_TOGGLE__": "help.knowledge_toggle",
    "__HELP_DIFF_OVERLAY__": "help.diff_overlay",
    "__HELP_EDGE_FLOW__": "help.edge_flow",
    "__HELP_COLLAPSE_CLUSTERS__": "help.collapse_clusters",
    "__HELP_TOUR_PREV_NEXT__": "help.tour_prev_next",
    "__HELP_TOUR_EXIT__": "help.tour_exit",
    "__HELP_CLOSE_HINT__": "help.close_hint",
}
