"""Zero-JavaScript static renderer: inline SVG embedded in HTML. Just a picture, no interactivity."""

from __future__ import annotations

import html
import math


def _radius(deg: int) -> float:
    return 3.5 + min(11.0, math.sqrt(deg) * 2.2)


def render_static_html(vm: dict) -> str:
    nodes = vm["nodes"]
    edges = vm["edges"]
    layers = vm["layers"]
    project = vm.get("project", {})
    stats = vm.get("stats", {})

    if nodes:
        xs = [n["x"] for n in nodes]
        ys = [n["y"] for n in nodes]
        minx, maxx = min(xs), max(xs)
        miny, maxy = min(ys), max(ys)
    else:
        minx = miny = 0
        maxx = maxy = 100
    pad = 60
    vb_x = minx - pad
    vb_y = miny - pad
    vb_w = (maxx - minx) + 2 * pad
    vb_h = (maxy - miny) + 2 * pad

    parts: list[str] = []
    # edges first (under nodes)
    parts.append('<g stroke="#334155" stroke-width="1" stroke-opacity="0.45">')
    for a, b in edges:
        na, nb = nodes[a], nodes[b]
        parts.append(f'<line x1="{na["x"]:.1f}" y1="{na["y"]:.1f}" x2="{nb["x"]:.1f}" y2="{nb["y"]:.1f}"/>')
    parts.append("</g>")
    # nodes
    parts.append("<g>")
    for n in nodes:
        r = _radius(n["deg"])
        parts.append(
            f'<circle cx="{n["x"]:.1f}" cy="{n["y"]:.1f}" r="{r:.1f}" fill="{n["color"]}" '
            f'stroke="#0b1220" stroke-width="0.7"><title>{html.escape(n["name"])}'
            f'{" — " + html.escape(n["path"]) if n["path"] else ""}</title></circle>'
        )
    parts.append("</g>")
    # labels for the most-connected nodes only (avoid clutter)
    hubs = sorted(nodes, key=lambda n: n["deg"], reverse=True)[:40]
    parts.append('<g fill="#cbd5e1" font-family="ui-monospace,monospace" font-size="11">')
    for n in hubs:
        if n["deg"] >= 3:
            parts.append(
                f'<text x="{n["x"] + _radius(n["deg"]) + 3:.1f}" y="{n["y"] + 3:.1f}">{html.escape(n["name"])}</text>'
            )
    parts.append("</g>")
    svg_inner = "\n".join(parts)

    legend_rows = "\n".join(
        f'<div class="lg"><span class="sw" style="background:{l["color"]}"></span>'
        f'<span class="nm">{html.escape(l["name"])}</span><span class="ct">{l["count"]}</span></div>'
        for l in layers
    )

    name = html.escape(project.get("name", "project"))
    subtitle = f'{stats.get("nodes", 0)} nodes · {stats.get("edges", 0)} edges · {len(layers)} layers (static)'

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>{name} · Knowledge Graph (static)</title>
<style>
  :root {{ color-scheme: dark; }}
  body {{ margin:0; background:#0b1220; color:#e2e8f0;
    font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,sans-serif; }}
  header {{ padding:16px 20px; border-bottom:1px solid #1e293b; }}
  header h1 {{ margin:0; font-size:18px; }} header .sub {{ color:#94a3b8; font-size:13px; margin-top:3px; }}
  .wrap {{ display:flex; gap:0; align-items:flex-start; }}
  .graph {{ flex:1; min-width:0; }} svg {{ width:100%; height:auto; display:block; background:#0b1220; }}
  aside {{ width:260px; flex:none; border-left:1px solid #1e293b; padding:16px; max-height:100vh; overflow:auto;
    position:sticky; top:0; }}
  aside h4 {{ margin:0 0 10px; font-size:11px; text-transform:uppercase; letter-spacing:.06em; color:#94a3b8; }}
  .lg {{ display:flex; align-items:center; gap:8px; padding:4px 2px; font-size:12px; }}
  .sw {{ width:11px; height:11px; border-radius:3px; flex:none; }}
  .lg .nm {{ flex:1; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }} .lg .ct {{ color:#64748b; }}
  footer {{ padding:10px 20px; color:#475569; font-size:11px; border-top:1px solid #1e293b; }}
</style></head>
<body>
<header><h1>{name}</h1><div class="sub">{subtitle}</div></header>
<div class="wrap">
  <div class="graph">
    <svg viewBox="{vb_x:.1f} {vb_y:.1f} {vb_w:.1f} {vb_h:.1f}" xmlns="http://www.w3.org/2000/svg">
{svg_inner}
    </svg>
  </div>
  <aside><h4>{len(layers)} layers</h4>{legend_rows}</aside>
</div>
<footer>Generated by understand-anything-py · static (zero-JavaScript) render. Hover a node for its name.</footer>
</body></html>
"""
