"""LLM-facing generated context artifacts."""

from __future__ import annotations

from pathlib import Path

from ..schema import COMPLEXITY_VALUES, EDGE_WEIGHTS, FILE_LEVEL_TYPES, NODE_TYPES
from .profiles import GeneratedOutput, OUTPUT_PROFILES


def build_llms_txt(root: Path, outputs: list[GeneratedOutput]) -> str:
    """Build a tiny LLM entrypoint that points agents to the right generated artifacts."""
    by_name = {item.path.name: item for item in outputs}
    lines = [
        f"# {root.name}",
        "",
        "> Generated by codeglance. Read this file first, then follow the smallest useful context tier.",
        "",
        "## Read Order",
    ]
    read_order = [
        ("agent.md", "compact repo map, read order, dependency hotspots, and agent rules"),
        ("onboarding.md", "human-friendly architecture walkthrough and first-day reading order"),
        ("impact.md", "changed-file impact report and dependency ripple checklist"),
        ("review.md", "graph and generated-output quality report before sharing or pushing"),
        ("llm-context.schema.json", "machine-readable contract for this output bundle"),
        ("knowledge-graph.toon", "compact TOON graph for LLM prompt context"),
        ("context.md", "full markdown map when compact context is not enough"),
        ("knowledge-graph.json", "complete graph for tools and structured retrieval"),
        ("glance.html", "interactive visual codebase map for inspection"),
        ("wiki.html", "human-readable architecture wiki"),
    ]
    for name, description in read_order:
        if name in by_name:
            lines.append(f"- `{name}` - {description}")
    lines.extend([
        "",
        "## Rules",
        "- Start with `agent.md`; do not read full source unless the map points to specific files.",
        "- Use `llm-context.schema.json` to understand artifact meanings and graph fields.",
        "- Use `knowledge-graph.toon` for compact prompt context; use JSON for parsers/tools.",
        "- Regenerate with `codeglance generate . --out .codeglance/outputs` after structural edits.",
    ])
    return "\n".join(lines).rstrip() + "\n"


def build_llm_context_schema(root: Path, outputs: list[GeneratedOutput]) -> dict:
    """Build the structured LLM contract for generated context artifacts."""
    generated = sorted(item.path.name for item in outputs)
    return {
        "schema": "codeglance.llm-context",
        "version": "1.0",
        "project": root.name,
        "purpose": "Help coding agents understand a repository with minimal token use before opening source.",
        "readOrder": [
            "llms.txt",
            "agent.md",
            "llm-context.schema.json",
            "context.md",
            "knowledge-graph.toon",
            "knowledge-graph.json",
            "selected source files",
        ],
        "generatedArtifacts": generated,
        "artifactContracts": [
            {
                "path": "llms.txt",
                "format": "text",
                "tier": 0,
                "audience": "agent",
                "contains": ["read order", "artifact pointers", "usage rules"],
            },
            {
                "path": "agent.md",
                "format": "markdown",
                "tier": 1,
                "audience": "agent",
                "contains": [
                    "snapshot",
                    "AI reading protocol",
                    "context budget",
                    "read-first files",
                    "architecture layers",
                    "changed files",
                    "dependency hotspots",
                ],
                "doesNotContain": ["full source code", "complete per-file catalog"],
            },
            {
                "path": "context.md",
                "format": "markdown",
                "tier": 2,
                "audience": "agent",
                "contains": ["read-first files", "file dependency map", "per-file summaries", "symbols"],
                "useWhen": "Use when agent.md is not enough to choose files.",
            },
            {
                "path": "onboarding.md",
                "format": "markdown",
                "tier": 2,
                "audience": "human-agent",
                "contains": ["project snapshot", "start-here files", "architecture layers", "guided reading order"],
                "useWhen": "Use when a human or agent needs a first-day walkthrough.",
            },
            {
                "path": "impact.md",
                "format": "markdown",
                "tier": 2,
                "audience": "human-agent",
                "contains": ["changed files", "ripple areas", "dependency ripples", "review checklist"],
                "useWhen": "Use before commit or review to understand likely affected areas.",
            },
            {
                "path": "review.md",
                "format": "markdown",
                "tier": 2,
                "audience": "human-agent",
                "contains": ["schema checks", "output freshness", "missing artifacts", "graph quality notes"],
                "useWhen": "Use before sharing or pushing generated Codeglance artifacts.",
            },
            {
                "path": "knowledge-graph.toon",
                "format": "toon",
                "tier": 3,
                "audience": "agent",
                "contains": ["project", "stats", "nodes table", "edges table", "layers table", "tour table"],
                "useWhen": "Use when an LLM needs structured graph context with fewer repeated field names than JSON.",
            },
            {
                "path": "knowledge-graph.json",
                "format": "json",
                "tier": 4,
                "audience": "tool",
                "contains": ["project", "nodes", "edges", "layers", "tour"],
                "useWhen": "Use for structured retrieval, graph traversal, and custom tools.",
            },
            {
                "path": "glance.html",
                "format": "html",
                "tier": "human",
                "audience": "human",
                "contains": ["interactive graph", "search", "filters", "guided tour"],
            },
        ],
        "agentProtocol": [
            "Read llms.txt and agent.md first.",
            "Inspect changed files before broad search.",
            "Follow dependency hotspots one hop at a time.",
            "Open source only after the generated map names specific files.",
            "Run targeted tests and regenerate outputs after code shape changes.",
        ],
        "knowledgeGraphSchema": {
            "version": "semantic version for this graph file",
            "project": {
                "name": "repository or folder name",
                "languages": "detected language ids",
                "frameworks": "detected framework ids",
                "description": "short generated repository summary",
                "analyzedAt": "ISO timestamp",
                "gitCommitHash": "current commit hash when available",
            },
            "nodes": {
                "id": "stable unique node id",
                "type": "one of nodeTypes",
                "name": "display name",
                "filePath": "repo-relative path when applicable",
                "summary": "short deterministic or LLM-enriched summary",
                "tags": "language/category/path tags",
                "complexity": "one of complexityValues",
                "lineRange": "optional [startLine, endLine]",
                "signature": "optional declaration signature",
                "docstring": "optional source docstring or leading comment",
            },
            "edges": {
                "source": "source node id",
                "target": "target node id",
                "type": "relationship type",
                "direction": "usually directed",
                "weight": "layout/relevance weight",
            },
            "layers": {
                "id": "stable layer id",
                "name": "architecture/group name",
                "description": "short layer summary",
                "nodeIds": "node ids in this layer",
            },
            "tour": {
                "order": "display order",
                "title": "tour step title",
                "description": "why this step matters",
                "nodeIds": "nodes to inspect",
            },
        },
        "nodeTypes": sorted(NODE_TYPES),
        "fileLevelNodeTypes": sorted(FILE_LEVEL_TYPES),
        "complexityValues": sorted(COMPLEXITY_VALUES),
        "edgeTypes": sorted(EDGE_WEIGHTS),
        "outputProfiles": {key: list(value) for key, value in OUTPUT_PROFILES.items()},
    }
